# Generated by Django 3.2.5 on 2021-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
