# Generated by Django 3.2.5 on 2021-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210730_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.IntegerField(null=True),
        ),
    ]
